name: "Release to production"

on:
  workflow_dispatch:

  release:
    types: [ published ]
    tags:
      - v*

jobs:
  deployment:
    name: Deploy to production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ~1.5

      #- name: Configure AWS Credentials
      #  id: aws
      #  uses: aws-actions/configure-aws-credentials@v2
      #  with:
      #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #    aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        env:
        # TF_WORKSPACE: production
        # TF_VAR_aws_region: ${{ secrets.AWS_REGION }}