name: Lint
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.run/**'
      - '.vscode/**'
      - 'config/**'
      - 'assets/**'

  pull_request:
    types: [ opened, synchronize ]
    paths-ignore:
      - '.run/**'
      - '.vscode/**'
      - 'config/**'
      - 'assets/**'
    branches:
      - main

  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version: 1.23.0

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v1.62
          args: --timeout=3m

  buf:
    name: Run buf
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: bufbuild/buf-action@v1
        with:
          github_token: ${{ github.token }}
