name: "Test service"
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '.run/**'
      - 'api/**'
      - 'features/**'
      - 'config/**'
      - 'deployments/**'
      - '*.md'
    tags:
      - v*
  pull_request:
    types: [ opened, synchronize ]
    paths-ignore:
      - 'docs/**'
      - '.run/**'
      - 'api/**'
      - 'features/**'
      - 'config/**'
      - 'deployments/**'
      - '*.md'
  workflow_dispatch:

jobs:

  # Generate mocks
  generate-mocks:
    name: "Generate mocks"
    runs-on: ubuntu-latest
    container: vektra/mockery:v2.38.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate mocks
        run: |
          mockery --all

      - name: Commit mocks
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Gen] Generated mocks"

  # Run unit tests
  tests:
    name: "Run unit tests"
    needs:
      - generate-mocks
    runs-on: ubuntu-latest
    steps:
      # todo add tests
      - name: Checkout
        uses: actions/checkout@v3

